name: Weekly Excel Automation Pipeline

on:
  schedule:
    - cron: '0 17 * * 5'
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11'

    - name: Install Data Libraries
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl matplotlib python-dotenv resend


      # 1. This generates the Excel file in the cloud environment
    - name: Execute Excel Engine
      run: python main.py

    # 2. This uploads the generated Excel file so it isn't deleted when the run ends
    - name: Save Generated Excel Report
      uses: actions/upload-artifact@v4
      with:
        name: sales-report
        path: output/sales_analysis_report.xlsx
